# Generated by Django 4.2.3 on 2023-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_autore_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='inserisci_immagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
