# Generated by Django 4.2.3 on 2023-07-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_inserisci_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='inserisci_immagine',
        ),
    ]
